App.focusedWindow()
sleep(1)
App.focus('Global')
App.focusedWindow()
sleep(1)
App.focus('GNU Image Manipulation Program')
App.focusedWindow()
sleep(1)
App.focus('Firefox.exe')
App.focusedWindow()
sleep(1)
App.focus('File')
App.focusedWindow()
sleep(1)
App.focus('Virgo')
App.focusedWindow()
sleep(1)
App.focus('Task Manager')
App.focusedWindow()
sleep(1)
App.focus('GNU Image Manipulation Program')
sleep(2)
App.focus('Global')
App.focus('GNU Image Manipulation Program')
sleep(2)
App.focus('Global')
